version: '3'
services:
  db:
    image: mysql:5.7.17
    container_name: app_db
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"


  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    image: app
    container_name: main_app
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && ./bin/server"
    volumes:
      - .:/var/www/VueApp
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=3306"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=password"
    ports:
      - "3000:3000"
      - 8080:8080
    depends_on:
      - db
    tty: true
