# version: '3'
# services:
#   # db:
#   #   image: postgres:10.1
#   #   container_name: app_db
#   #   environment:
#   #     - "POSTGRES_USER=root"
#   #     - "POSTGRES_PASSWORD=root"
#   #   ports:
#   #     - "5432:5432"
#   # mysql:
#   #   image: mysql:8.0.12
#   #   ports:
#   #     - 3307:3306
#   #   restart: on-failure
#   #   environment:
#   #     MYSQL_DATABASE: sample_docker_development
#   #     MYSQL_ROOT_PASSWORD: root
#   db:
#     image: mysql:8.0.12
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./docker/mysql/volumes:/var/lib/mysql
#     extends:
#       file: ./docker/mysql/password.yml
#       service: password
#   web:
#     build: .
#     image: app
#     container_name: main_app
#     command: /bin/sh -c "rm -f ./tmp/pids/server.pid && ./bin/server"
#     volumes:
#       - .:/var/www/VueApp
#     environment:
#       - "DATABASE_HOST=db"
#       - "DATABASE_PORT=5432"
#       - "DATABASE_USER=root"
#       - "DATABASE_PASSWORD=root"
#     ports:
#       - "3000:3000"
#       - 8080:8080
#     depends_on:
#       - db

version: '2'
services:
  db:
    image: mysql:5.7.17
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    extends:
      file: /Users/rintaro.yokoyama/achievement/-Achievement_Rintaro/docker-rails/docker/mysql/password.yml
      service: password
  web:
    build:
      context: .
      dockerfile: /Users/rintaro.yokoyama/achievement/-Achievement_Rintaro/docker-rails/docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: development
    extends:
      file: /Users/rintaro.yokoyama/achievement/-Achievement_Rintaro/docker-rails/docker/mysql/password.yml
      service: password
    depends_on:
      - db
